BEIGE = "E7C1A4"
BLUE = "B4C6E7"
BLUE_BRIGHT = "0078D4"
RED_BRIGHT = "C00000"
WHITE = "FFFFFF"
BLACK = "000000"
GREY = "333333"
YELLOW = "FFD966"

COLUMN_COLORS = {
    "RFC_EMISOR": RED_BRIGHT,
    "IDENTIFICADO": RED_BRIGHT,
    "ESTATUS_EDICOM": BEIGE,

    "TIPO DE COMPROBANTE": BEIGE,
    "SERIE": BEIGE,
    "FOLIO": BEIGE,
    "FECHA REAL": BEIGE,
    "FECHA DOCUMENTO": BEIGE,
    "UUID": BEIGE,
    "SUBTOTAL": BEIGE,
    "IVA": BEIGE,
    "TOTAL": BEIGE,
    "RECEPTOR RFC": BEIGE,
    "RECEPTOR NOMBRE": BEIGE,
    "METODO DE PAGO": BEIGE,
    "MONEDA": BEIGE,
    "CONTRATO": BEIGE,
    "OBSERVACIONES": BEIGE,
    "CONCEPTO": BEIGE,
    "TOTAL CONCEPTO": BEIGE,
    "CÓDIGO PRODUCTO": BEIGE,

    "Periodo": BLUE,
    "Día": BLUE,
    "Mes": BLUE,
    "Fecha": BLUE,

    "Tipo de cambio": RED_BRIGHT,

    "UUID METADATA": BLUE_BRIGHT,
    "TOTAL METADATA": BLUE_BRIGHT,
    "FECHA EMISIÓN METADATA": BLUE_BRIGHT,
    "PERIODO": BLUE_BRIGHT,
    "ESTATUS METADATA": BLUE_BRIGHT,

    "ESTATUS": BLUE,
    "TOTAL CONCEPTO MXN": BLUE,
    "ESTATUS REPORTE INTERNO VS METADATA": BLUE,
    "FECHA DE CANCELACIÓN": BLUE_BRIGHT,
    "CONTRATO (CLAVE)": BLUE,
    "PREFIJO": BLUE,
    "% DE IVA": BLUE,
    "Contrato MID": BLUE,

    "% DE IVA POR CONCEPTO": RED_BRIGHT,
    "USO CFDI": RED_BRIGHT,
}

COLUMN_GROUPS = {
    "RFC_EMISOR": "CONTROL WINBA",
    "IDENTIFICADO": "CONTROL WINBA",
    "ESTATUS_EDICOM": "EDICOM",

    "TIPO DE COMPROBANTE": "EDICOM",
    "SERIE": "EDICOM",
    "FOLIO": "EDICOM",
    "FECHA REAL": "EDICOM",
    "FECHA DOCUMENTO": "EDICOM",
    "UUID": "EDICOM",
    "SUBTOTAL": "EDICOM",
    "IVA": "EDICOM",
    "TOTAL": "EDICOM",
    "RECEPTOR RFC": "EDICOM",
    "RECEPTOR NOMBRE": "EDICOM",
    "METODO DE PAGO": "EDICOM",
    "MONEDA": "EDICOM",
    "CONTRATO": "EDICOM",
    "OBSERVACIONES": "EDICOM",
    "CONCEPTO": "EDICOM",
    "TOTAL CONCEPTO": "EDICOM",
    "CÓDIGO PRODUCTO": "EDICOM",

    "Periodo": "FORMULADO",
    "Día": "FORMULADO",
    "Mes": "FORMULADO",
    "Fecha": "FORMULADO",

    "Tipo de cambio": "WINBA",

    "UUID METADATA": "FACTURACION SAT",
    "TOTAL METADATA": "FACTURACION SAT",
    "FECHA EMISIÓN METADATA": "FACTURACION SAT",
    "PERIODO": "FACTURACION SAT",
    "ESTATUS METADATA": "FACTURACION SAT",

    "ESTATUS": "FORMULADO",
    "TOTAL CONCEPTO MXN": "FORMULADO",
    "ESTATUS REPORTE INTERNO VS METADATA": "FORMULADO",

    "FECHA DE CANCELACIÓN": "METADATA",

    "CONTRATO (CLAVE)": "FORMULADO",
    "PREFIJO": "FORMULADO",
    "% DE IVA": "FORMULADO",

    "% DE IVA POR CONCEPTO": "WINBA",
    "USO CFDI": "WINBA",
    "Contrato MID": "FORMULADO",
}

GROUP_COLORS = {
    "WINBA": RED_BRIGHT,
    "CONTROL WINBA": RED_BRIGHT,
    "EDICOM": BEIGE,
    "FORMULADO": BLUE,
    "FACTURACION SAT": BLUE_BRIGHT,
    "METADATA": BLUE_BRIGHT,
}