BEIGE = "E7C1A4"
BLUE = "B4C6E7"
RED_BRIGHT = "FF1A1A"
WHITE = "FFFFFF"
BLACK = "000000"

COLUMN_COLORS = {
    "RFC_EMISOR": BEIGE,
    "IDENTIFICADO": BEIGE,
    "ESTATUS_EDICOM": BEIGE,

    "TIPO DE COMPROBANTE": BEIGE,
    "SERIE": BEIGE,
    "FOLIO": BEIGE,
    "FECHA REAL": BEIGE,
    "FECHA DOCUMENTO": BEIGE,
    "UUID": BEIGE,
    "SUBTOTAL": BEIGE,
    "IVA": BEIGE,
    "TOTAL": BEIGE,
    "RECEPTOR RFC": BEIGE,
    "RECEPTOR NOMBRE": BEIGE,
    "METODO DE PAGO": BEIGE,
    "MONEDA": BEIGE,
    "CONTRATO": BEIGE,
    "OBSERVACIONES": BEIGE,
    "CONCEPTO": BEIGE,
    "TOTAL CONCEPTO": BEIGE,
    "CÓDIGO PRODUCTO": BEIGE,

    "Periodo": BLUE,
    "Día": BLUE,
    "Mes": BLUE,
    "Fecha": BLUE,

    "Tipo de cambio": RED_BRIGHT,

    "UUID METADADA": BLUE,
    "TOTAL METADATA": BLUE,
    "FECHA EMISIÓN METADATA": BLUE,
    "PERIODO": BLUE,
    "ESTATUS METADATA": BLUE,

    "ESTATUS": BLUE,
    "TOTAL CONCEPTO MXN": BLUE,
    "ESTATUS REPORTE INTERNO VS METADATA": BLUE,
    "FECHA DE CANCELACIÓN": BLUE,
    "CONTRATO (CLAVE)": BLUE,
    "PREFIJO": BLUE,
    "% DE IVA": BLUE,
    "Contrato MID": BLUE,

    "% DE IVA POR CONCEPTO": RED_BRIGHT,
    "USO CFDI": RED_BRIGHT,
}